// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttakjgujxoxyuepjxpoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YWtqZ3VqeG94eXVlcGp4cG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTE4NDIsImV4cCI6MjA1Nzg4Nzg0Mn0.eYKI4Ow3DdSy-6WW3XxbKrBMAngm4HNd2UdjCOVImqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);